// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace SMEPMLBackML.Model
{
    public class ModelInput
    {
        [ColumnName("ENFERMEDAD"), LoadColumn(0)]
        public string ENFERMEDAD { get; set; }


        [ColumnName("SINTOMA1"), LoadColumn(1)]
        public string SINTOMA1 { get; set; }


        [ColumnName("SINTOMA2"), LoadColumn(2)]
        public string SINTOMA2 { get; set; }


        [ColumnName("SINTOMA3"), LoadColumn(3)]
        public string SINTOMA3 { get; set; }


    }
}
