// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Infrastructure.Services
{
    public class ModelInput
    {
        [LoadColumn(0)]
        public string ENFERMEDAD { get; set; }
        [LoadColumn(1)]
        public string SINTOMA { get; set; }
    }
}
