// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace Infrastructure.Services
{
    public class ModelOutput
    {
        [ColumnName("PredictedLabel")]
        public string ENFERMEDAD;
    }
}
