// This file was auto-generated by ML.NET Model Builder. 

using System;
using SMEPMLBackML.Model;

namespace SMEPMLBackML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                SINTOMA1 = @"Dolor o ardor en la parte superior del abdomen",
                SINTOMA2 = @"N�useas",
                SINTOMA3 = @"V�mitos",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual ENFERMEDAD with predicted ENFERMEDAD from sample data...\n\n");
            Console.WriteLine($"SINTOMA1: {sampleData.SINTOMA1}");
            Console.WriteLine($"SINTOMA2: {sampleData.SINTOMA2}");
            Console.WriteLine($"SINTOMA3: {sampleData.SINTOMA3}");
            Console.WriteLine($"\n\nPredicted ENFERMEDAD value {predictionResult.Prediction} \nPredicted ENFERMEDAD scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
